server {
    listen 8080;
    root /usr/share/nginx/html;
    index pages/index.html;

    location / {
        try_files $uri $uri/ /pages/index.html;
    }
    location /pages/ {
        try_files $uri =404;
    }
    location /src/ {
        try_files $uri =404;
    }
}
